# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mm4rk3t/IsoMateric

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mm4rk3t/IsoMateric

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.0.1-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mm4rk3t/IsoMateric/CMakeFiles /home/mm4rk3t/IsoMateric//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mm4rk3t/IsoMateric/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IsoMateric

# Build rule for target.
IsoMateric: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IsoMateric
.PHONY : IsoMateric

# fast build rule for target.
IsoMateric/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/build
.PHONY : IsoMateric/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f IsoMateric/vendor/glfw/CMakeFiles/uninstall.dir/build.make IsoMateric/vendor/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f IsoMateric/vendor/glfw/src/CMakeFiles/glfw.dir/build.make IsoMateric/vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f IsoMateric/vendor/assimp/code/CMakeFiles/assimp.dir/build.make IsoMateric/vendor/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

IsoMateric/src/application.o: IsoMateric/src/application.cpp.o
.PHONY : IsoMateric/src/application.o

# target to build an object file
IsoMateric/src/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/application.cpp.o
.PHONY : IsoMateric/src/application.cpp.o

IsoMateric/src/application.i: IsoMateric/src/application.cpp.i
.PHONY : IsoMateric/src/application.i

# target to preprocess a source file
IsoMateric/src/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/application.cpp.i
.PHONY : IsoMateric/src/application.cpp.i

IsoMateric/src/application.s: IsoMateric/src/application.cpp.s
.PHONY : IsoMateric/src/application.s

# target to generate assembly for a file
IsoMateric/src/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/application.cpp.s
.PHONY : IsoMateric/src/application.cpp.s

IsoMateric/src/isomateric.o: IsoMateric/src/isomateric.cpp.o
.PHONY : IsoMateric/src/isomateric.o

# target to build an object file
IsoMateric/src/isomateric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/isomateric.cpp.o
.PHONY : IsoMateric/src/isomateric.cpp.o

IsoMateric/src/isomateric.i: IsoMateric/src/isomateric.cpp.i
.PHONY : IsoMateric/src/isomateric.i

# target to preprocess a source file
IsoMateric/src/isomateric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/isomateric.cpp.i
.PHONY : IsoMateric/src/isomateric.cpp.i

IsoMateric/src/isomateric.s: IsoMateric/src/isomateric.cpp.s
.PHONY : IsoMateric/src/isomateric.s

# target to generate assembly for a file
IsoMateric/src/isomateric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/isomateric.cpp.s
.PHONY : IsoMateric/src/isomateric.cpp.s

IsoMateric/src/renderer.o: IsoMateric/src/renderer.cpp.o
.PHONY : IsoMateric/src/renderer.o

# target to build an object file
IsoMateric/src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/renderer.cpp.o
.PHONY : IsoMateric/src/renderer.cpp.o

IsoMateric/src/renderer.i: IsoMateric/src/renderer.cpp.i
.PHONY : IsoMateric/src/renderer.i

# target to preprocess a source file
IsoMateric/src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/renderer.cpp.i
.PHONY : IsoMateric/src/renderer.cpp.i

IsoMateric/src/renderer.s: IsoMateric/src/renderer.cpp.s
.PHONY : IsoMateric/src/renderer.s

# target to generate assembly for a file
IsoMateric/src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/renderer.cpp.s
.PHONY : IsoMateric/src/renderer.cpp.s

IsoMateric/src/resourceManager.o: IsoMateric/src/resourceManager.cpp.o
.PHONY : IsoMateric/src/resourceManager.o

# target to build an object file
IsoMateric/src/resourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/resourceManager.cpp.o
.PHONY : IsoMateric/src/resourceManager.cpp.o

IsoMateric/src/resourceManager.i: IsoMateric/src/resourceManager.cpp.i
.PHONY : IsoMateric/src/resourceManager.i

# target to preprocess a source file
IsoMateric/src/resourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/resourceManager.cpp.i
.PHONY : IsoMateric/src/resourceManager.cpp.i

IsoMateric/src/resourceManager.s: IsoMateric/src/resourceManager.cpp.s
.PHONY : IsoMateric/src/resourceManager.s

# target to generate assembly for a file
IsoMateric/src/resourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/resourceManager.cpp.s
.PHONY : IsoMateric/src/resourceManager.cpp.s

IsoMateric/src/shader.o: IsoMateric/src/shader.cpp.o
.PHONY : IsoMateric/src/shader.o

# target to build an object file
IsoMateric/src/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/shader.cpp.o
.PHONY : IsoMateric/src/shader.cpp.o

IsoMateric/src/shader.i: IsoMateric/src/shader.cpp.i
.PHONY : IsoMateric/src/shader.i

# target to preprocess a source file
IsoMateric/src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/shader.cpp.i
.PHONY : IsoMateric/src/shader.cpp.i

IsoMateric/src/shader.s: IsoMateric/src/shader.cpp.s
.PHONY : IsoMateric/src/shader.s

# target to generate assembly for a file
IsoMateric/src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/shader.cpp.s
.PHONY : IsoMateric/src/shader.cpp.s

IsoMateric/src/texture.o: IsoMateric/src/texture.cpp.o
.PHONY : IsoMateric/src/texture.o

# target to build an object file
IsoMateric/src/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/texture.cpp.o
.PHONY : IsoMateric/src/texture.cpp.o

IsoMateric/src/texture.i: IsoMateric/src/texture.cpp.i
.PHONY : IsoMateric/src/texture.i

# target to preprocess a source file
IsoMateric/src/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/texture.cpp.i
.PHONY : IsoMateric/src/texture.cpp.i

IsoMateric/src/texture.s: IsoMateric/src/texture.cpp.s
.PHONY : IsoMateric/src/texture.s

# target to generate assembly for a file
IsoMateric/src/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/src/texture.cpp.s
.PHONY : IsoMateric/src/texture.cpp.s

IsoMateric/vendor/glad/src/glad.o: IsoMateric/vendor/glad/src/glad.c.o
.PHONY : IsoMateric/vendor/glad/src/glad.o

# target to build an object file
IsoMateric/vendor/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/vendor/glad/src/glad.c.o
.PHONY : IsoMateric/vendor/glad/src/glad.c.o

IsoMateric/vendor/glad/src/glad.i: IsoMateric/vendor/glad/src/glad.c.i
.PHONY : IsoMateric/vendor/glad/src/glad.i

# target to preprocess a source file
IsoMateric/vendor/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/vendor/glad/src/glad.c.i
.PHONY : IsoMateric/vendor/glad/src/glad.c.i

IsoMateric/vendor/glad/src/glad.s: IsoMateric/vendor/glad/src/glad.c.s
.PHONY : IsoMateric/vendor/glad/src/glad.s

# target to generate assembly for a file
IsoMateric/vendor/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IsoMateric.dir/build.make CMakeFiles/IsoMateric.dir/IsoMateric/vendor/glad/src/glad.c.s
.PHONY : IsoMateric/vendor/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... IsoMateric"
	@echo "... assimp"
	@echo "... glfw"
	@echo "... IsoMateric/src/application.o"
	@echo "... IsoMateric/src/application.i"
	@echo "... IsoMateric/src/application.s"
	@echo "... IsoMateric/src/isomateric.o"
	@echo "... IsoMateric/src/isomateric.i"
	@echo "... IsoMateric/src/isomateric.s"
	@echo "... IsoMateric/src/renderer.o"
	@echo "... IsoMateric/src/renderer.i"
	@echo "... IsoMateric/src/renderer.s"
	@echo "... IsoMateric/src/resourceManager.o"
	@echo "... IsoMateric/src/resourceManager.i"
	@echo "... IsoMateric/src/resourceManager.s"
	@echo "... IsoMateric/src/shader.o"
	@echo "... IsoMateric/src/shader.i"
	@echo "... IsoMateric/src/shader.s"
	@echo "... IsoMateric/src/texture.o"
	@echo "... IsoMateric/src/texture.i"
	@echo "... IsoMateric/src/texture.s"
	@echo "... IsoMateric/vendor/glad/src/glad.o"
	@echo "... IsoMateric/vendor/glad/src/glad.i"
	@echo "... IsoMateric/vendor/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

